# FAISS
https://lsjsj92.tistory.com/605

In [1]:
import pandas as pd
import numpy as np
import faiss

In [6]:
"""
vector 유사도 계산
빠르고 강력

sample
: 20개의 vector 32 dim으로 구성

"""

vector_sample = np.random.rand(20,32).astype('float32')
shape = vector_sample.shape
shape

(20, 32)

In [10]:
# faiss의 IndexFlatL2함수를 호출해서 백터의 차원이 어떻게 되는지 알려준다.
# faiss의 객체에 대해서 add함수로 vector값을 넣어주면 된다.
 
    
    

index = faiss.IndexFlatL2(shape[1]) # dim 32
print(index.ntotal)

index.add(vector_sample) 
# faiss 내부에서 백터 유사도를 계산 완료
print(index.ntotal)


0
20


In [29]:
""" 
0번 백터와 나머지 사이의 유사도를 확인했을 때,
유사한 순서대로 3개 뽑아낸것
distance, indeices
"""

distance, indeices = index.search(x = vector_sample[0].reshape(1,-1),
                                  k = 3)
# x: 기준 백터, k: 가장 유사한 3개의 값을 가지고옴

In [47]:
import random
ids = np.arange(40,60)
random.shuffle(ids)
print(ids)

[41 48 54 53 45 46 50 57 49 58 40 59 43 47 51 44 55 56 42 52]


In [48]:
index = faiss.IndexFlatL2(vector_sample.shape[1])
print(index)
index = faiss.IndexIDMap2(index)
print(index)
index.add_with_ids(vector_sample, ids)

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7feeae2f7570> >
<faiss.swigfaiss_avx2.IndexIDMap2; proxy of <Swig Object of type 'faiss::IndexIDMap2 *' at 0x7feeae2f7600> >


In [49]:
distances, indices = index.search(vector_sample[0].reshape(1, -1), 3)

In [50]:
distances

array([[0.       , 4.7064877, 4.8350773]], dtype=float32)

In [51]:
indices

array([[41, 57, 50]])